services:
  timescaledb:
    image: timescale/timescaledb:2.12.2-pg15
    container_name: timescaledb-tutorial-db
    restart: unless-stopped
    ports:
      - "127.0.0.1:15432:5432"
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./timescaledb/setup.sh:/docker-entrypoint-initdb.d/setup.sh

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: timescaledb-tutorial-pgadmin
    restart: unless-stopped
    ports:
      - "127.0.0.1:15433:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
    pgdata:
    pgadmin-data:
