---
default_language_version:
  python: python3.12
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [commit]
fail_fast: false
minimum_pre_commit_version: 3.5.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.5"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/ambv/black
    rev: "23.11.0"
    hooks:
      - id: black
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "1.5.1"
    hooks:
      - id: pyproject-fmt
        args: ["--indent=4"]
  - repo: https://github.com/jorisroovers/gitlint
    rev: "v0.19.1"
    hooks:
      - id: gitlint
        language: python
        language_version: python3.11
